- pyheos/const.py
- pyheos/player.py
- tests/test_player.py
Support minimal payload in `get_players` response.
**Related issue (if applicable):** home-assistant/home-assistant#23557
> Support minimal get_players payload

- pyheos/const.py
- pyheos/player.py
- tests/fixtures/player.get_now_playing_media_blank.json
- tests/test_player.py
- Fix edge case where `get_now_playing_media` returns an empty payload
**Related issue (if applicable):** source home-assistant/home-assistant#23640
> Release 0.5.2

- README.md
- pyheos/const.py
Added more input sources per CLI v1.16 spec here: https://rn.dmglobal.com/usmodel/HEOS_CLI_ProtocolSpecification-Version-1.16.pdf
**Related issue (if applicable):**
> Update inputs for CLI 1.16 to support TV and 8K sources

- README.md
- pyheos/const.py
Update the available inputs for the [HEOS CLI Protocol Specification Version 1.17](https://rn.dmglobal.com/usmodel/HEOS_CLI_ProtocolSpecification-Version-1.17.pdf). Sorted input variables alphabetically to improve maintainability.
> HEOS CLI Protocol Specification 1.17 Updates

- pyheos/connection.py
Reconnect logic improved, it could fail because the state was set to connected before the connect function had called the register_for_change_events function, and if that failed an error was raised and the state remained connected while it was actually not really. So state is set back to reconnecting in _reconnect when this happens.
Also catching AttributeError in command function which sometimes occurs when _writer object is None (which can happen sometimes during reconnect process).
See also https://github.com/andrewsayre/pyheos/pull/21 for additional stability improvements.
**Related issue (if applicable):** fixes #20
> Fix for incorrect connection status

- README.md
- pyheos/command.py
- pyheos/const.py
- pyheos/error.py
- pyheos/group.py
- pyheos/heos.py
- pyheos/message.py
- pyheos/player.py
- pyheos/source.py
- pyheos/system.py
- tests/__init__.py
- tests/fixtures/player.get_players.json
- tests/fixtures/player.get_players_changed.json
- tests/fixtures/player.get_players_firmware_update.json
- tests/test_group.py
- tests/test_heos.py
- tests/test_player.py
- tests/test_source.py
Adds a new function to get the HEOS system information and logic for preferred hosts. Also organized and cleaned-up constants.
**Related issue (if applicable):** fixes #<pyheos issue number goes here>
> Add feature to test a connection and obtain system info

- pyheos/heos.py
- tests/test_heos.py
Adds the ability to update the stored credentials when using the `sign_in` and `sign_out` functions of the `Heos` class:
* New optional parameter `update_credential` added to functions `Heos.sign_in` and `Heos.sign_out` with default value of `True`. When `True`, the stored credentials will be updated upon successful sign-in (replaced) or sign-out (cleared). These updated credentials will be used during reconnection, if auto-reconnect is enabled. If set to `False`, the stored credentials will remain unchanged.
* New property `Heos.current_credentials` exposes the currently stored crednetials, whether passed in through options, or updated as the result of a `sign_in` or `sign_out` call.
> Add ability to update credentials

- pyheos/__init__.py
- pyheos/command/__init__.py
- pyheos/command/browse.py
- pyheos/command/player.py
- pyheos/const.py
- pyheos/heos.py
- pyheos/player.py
- tests/fixtures/player.get_now_playing_media.json
- tests/test_heos.py
- tests/test_player.py
Refactors player commands, following the same model as was done for browse commands.
- Change `HeosNowPlayingMedia` to a dataclass. No public members were changed.
- Add `PlayMode` for representing play mode instead of using tuple.
Adds new class: 
**Related issue (if applicable):** fixes #43
> Refactor player commands

- pyheos/message.py
- tests/fixtures/browse.play_stream.json
- tests/test_player.py
Before this change, if I request to play the URL
http://192.168.0.10/test.mp3?auth=something
through Home Assistant, it will result in this message being sent:
heos://browse/play_stream?sequence=498&pid=-646915758&url=http://192.168.0.10/test.mp3?auth%3Dsomething
but despite saying in CLI specification that special characters in arguments need to be encoded, HEOS seems to take the url argument and pass it to the stream server verbatim, as demonstrated by the nginx log resulting from this command:
Jan 04 12:03:27 lillia nginx[351316]: lillia nginx: 192.168.0.209 - - [04/Jan/2025:12:03:27 +0100] "GET /test.mp3?auth%3Dsomething HTTP/1.1" 404 146 "-" "AvegaMediaServer/2.0 Linux/2.6"
I've been playing URLs with ? in them for some months now by inserting them into the HEOS command without …
> Change message encoding to support URLs with ?

- .devcontainer/devcontainer.json
- .github/workflows/ci.yaml
- .github/workflows/publish.yaml
- pyproject.toml
- test-requirements.txt
Add to build matrix, update dev container environment, and update all dependency packages.
Fixes: #38
> Add Python 3.13 support

- pyheos/connection.py
- pyheos/dispatch.py
- pyheos/heos.py
- tests/fixtures/event.invalid.json
- tests/test_dispatch.py
- tests/test_heos.py
Wraps command responses and checks if they are an auth-related failure, and if so sends `EVENT_USER_CREDENTIALS_INVALID`. Modified dispatcher to track tasks and created ability to wait or cancel all.
**Related issue (if applicable):** fixes #53
> Feature auth failure eventing

- pyheos/connection.py
- tests/test_heos.py
Moves the invocation of the `command_error` callbacks outside of the held lock for commands so that other commands could be called within the callback.
**Related issue (if applicable):** fixes #58
> Fix deadlock when calling command within command_error handler

- pyheos/command/__init__.py
- pyheos/command/group.py
- pyheos/group.py
- pyheos/heos.py
- pyproject.toml
- tests/conftest.py
- tests/fixtures/group.get_group_info.json
- tests/test_group.py
- tests/test_heos.py
Adds the ability to get an individual group or refresh it's base values.
- Added `get_group_info` method to retrieve or refresh a specific group. If all groups are loaded, this will retrieve the cached instance, unless refresh=True.
- Added parameter `refresh_base_info: bool = True` to `refresh` method to include updating the base information about the group (name, id, leader, members) in addition to mute and volume.
**Related issue (if applicable):** fixes #60
> Add remaining Group commands

- pyheos/command/__init__.py
- pyheos/command/player.py
- pyheos/heos.py
- pyheos/player.py
- tests/fixtures/player.get_player_info.json
- tests/fixtures/player.get_players.json
- tests/test_heos.py
- tests/test_player.py
Implements the Get Player Info command and ability to refresh the data of a player.
- Added `get_player_info` function to retrieve a specific player and optionally refresh and update an existing instance.
- Added parameter `refresh_base_info: bool = True` to `refresh` to optionally pull the latest player information, such as name.
- Added `group_id` field to represent the group reference the player is a member of, otherwise None.
**Related issue (if applicable):** link: #62
> Add Get Player Info

- pyheos/command/__init__.py
- pyheos/player.py
- pyheos/system.py
- pyheos/types.py
- tests/conftest.py
- tests/fixtures/player.get_players.json
- tests/test_heos.py
- tests/test_player.py
- New `control` property to indicate the volume control type when `lineout` is Fixed.
- `lineout` is now an enum of type `LineOutLevelType`
- Added `LineOutLevelType` and `VolumeControlType`
**Related issue (if applicable):** closes: #72
> Add enums for player fields

- pyheos/connection.py
Adds incremental backoff logic to the reconnection task, with a ceiling of 10min. This also means that the maximum reconnect delay can be 10min.
**Related issue (if applicable):** fixes #77
> Add incremental backoff

- pyheos/const.py
- pyheos/heos.py
- pyheos/player.py
- tests/fixtures/browse.add_to_queue_search.json
- tests/test_player.py
Adds helper function for adding searched content to the queue. Currently HEOS only supports tracks.
- Added `add_search_to_queue` to add items to the queue for the specified player based on the search string.
- Added `add_search_to_queue` to add items to the queue for the current player based on the search string.
**Related issue (if applicable):** closes #79
> Add add_search_to_queue

- pyheos/command/player.py
- pyheos/heos.py
- tests/fixtures/player.get_players_no_groups.json
- tests/test_heos.py
Ensures that players are refreshed after groups change so that `group_id` and any other attributes are updated (only if players have been loaded.)
**Related issue (if applicable):** fixes #86
> Refresh players after group event

- pyheos/connection.py
Simplifies the try/except logic in the heart beat handler.
**Related issue (if applicable):** fixes #<pyheos issue number goes here>
> Simplify heart beat loop logic

- pyheos/command/__init__.py
- pyheos/player.py
- tests/snapshots/test_heos.ambr
- tests/snapshots/test_player.ambr
Updates the `HeosNowPlayingMedia` class so that `type` is of type `MediaType` instead of a string.
**Related issue (if applicable):** fixes #<pyheos issue number goes here>
> Use enum for HeosNowPlayingMedia.type

- pyheos/connection.py
- tests/test_heos.py
Makes some minor improvements to the connection logic:
- Names tasks 
- Uses `suppress` instead of `try/except/pass`
- Removes unnecessary catching of derived exceptions (e.g. `ConnectionError` is derived from `OSError` which we were also catching)
- Modified test to wait out reconnect task
- Test coverage is now 100% 
**Related issue (if applicable):** fixes #<pyheos issue number goes here>
- [X ] Tests have been added/updated. No exclusions in `.coveragerc` permitted.
> Minor improvements to Connection

- pyheos/connection.py
- tests/__init__.py
- tests/test_heos.py
Fixes inability to recover when a command response is received after the timeout period and the original caller has timed out and is no longer waiting for the response. Also improves handling/tracking of incoming responses so that if unexpected responses are received, they are logged and ignored. 
**Related issue (if applicable):** fixes #98
> Fix handling of command timeouts

- pyheos/connection.py
- tests/fixtures/player.get_now_playing_media_failed.json
- tests/test_heos.py
Adds a task done callback to ensure that uncaught errors in callbacks are logged.
> Ensure uncaught errors in connection tasks are logged

- pyheos/heos.py
- tests/__init__.py
- tests/test_heos.py
After reconnecting, this ensures that both players and groups are refreshed; the player update result is sent via event signal, and all signals that arise during reconnection are sent at the end, to ensure all data is updated and present when consumers begin reacting against the updated data.
> Ensure players and groups refresh after reconnect

- pyheos/util/__init__.py
- pyheos/util/mediauri.py
- tests/util/__init__.py
- tests/util/test_mediauri.py
Adds a new utility module for serializing and deserializing media items to/from URIs. This is useful to represent these instances as a string.
> Add media URI serialization utilities

- README.md
- pyheos/command/connection.py
- pyheos/connection.py
- pyheos/heos.py
- pyheos/options.py
- pyheos/system.py
- tests/__init__.py
- tests/test_heos_autofailover.py
Adds a new feature to automatically failover to alternate system hosts when the connected host goes down. When enabled, the connection will maintain a list of alternate hosts and cycle through them until connected. After a disconnection, it will first attempt to reconnect to the current host once before moving on to the next host. When the functionality is disabled (the default), or there are no alternate hosts, the connection will fallback to the previous reconnect logic.
Three new parameters have been added to HEOS options:
- `auto_failover: bool`: Set to True to automatically failover to other hosts if the connection is lost. The default is False.
- `auto_failover_hosts: Sequence[str]`: A sequence of failover host names. If not provided, they will be automatically populated and updated …
> Add auto-failover feature

- pyheos/command/browse.py
- tests/snapshots/test_heos.ambr
- tests/test_heos.py
Allow browsing of `MediaMusicSource` instances that are not `available`, since they can still be enumerated, and in the case of TuneIn, browsed and played. 
**Related issue (if applicable):** fixes #113
> Allow browsing unavailable sources

- pyheos/heos.py
- tests/test_heos.py
This ensures that loaded music sources are refreshed when a user changed event is received, as that changes the availability of the items.
> Update music sources when user changes

- pyproject.toml
[PEP 639](https://peps.python.org/pep-0639/) added support for SPDX license expressions.
I believe the correct one here is `Apache-2.0`: https://spdx.org/licenses/Apache-2.0.html
> Use SPDX license identifier for project metadata

- pyheos/command/player.py
- pyheos/types.py
- tests/test_player.py
The result of `get_play_state` may return `unknown`, which was not defined in the enumeration. This appears to occur when media has been paused for an extended time and HEOS itself loses track of the state of the play. This change the unknown option to the enumeration and prevents setting that in `set_play_state`.
**Related issue (if applicable):** Discovered in https://github.com/home-assistant/core/issues/142420
> Add unknown play state enumeration
